/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project1;

/**
 *
 * @author HP
 */
import java.sql.*;
import static project1.bruhhhhh.con;
import static project1.bruhhhhh.stm;
public class login extends javax.swing.JFrame {
    public static Connection con;
    public static Statement stm;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nimm = new javax.swing.JTextField();
        pinn = new javax.swing.JTextField();
        VALIDATE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nimm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimmActionPerformed(evt);
            }
        });

        pinn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinnActionPerformed(evt);
            }
        });

        VALIDATE.setText("LOGIN BANGGG");
        VALIDATE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        VALIDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VALIDATEActionPerformed(evt);
            }
        });
        VALIDATE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VALIDATEKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Masukan PIN Anda :");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Masukan NIM Anda :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(VALIDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nimm, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pinn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 332, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nimm, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(pinn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(VALIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimmActionPerformed

    private void pinnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinnActionPerformed

    private void VALIDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VALIDATEActionPerformed
            // TODO add your handling code here:
        login loginValidation = new login();
        String nim = nimm.getText();
        String pin = pinn.getText();

        if (login.validateLogin(nim, pin)) {
            System.out.println("Login berhasil!");
            bruhhhhh myFrame = new bruhhhhh();
            myFrame.setVisible(true);
            this.dispose();
        } else {
            System.out.println("Login gagal. NIM atau PIN salah.");
            hapus();
        }
    }//GEN-LAST:event_VALIDATEActionPerformed

    private void VALIDATEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VALIDATEKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_VALIDATEKeyPressed

    public static boolean validateLogin(String Nim, String Pin) {
        boolean isValid = false;
        Connection connection = null;
        PreparedStatement statement = null;
        ResultSet resultSet = null;

        try {
            // Buatlah koneksi dengan database
            String url = "jdbc:mysql://localhost/belajar_sql";
            String user = "root";
            String pass = "23050477";
            
            con = DriverManager.getConnection(url, user, pass);
            stm = con.createStatement();
            System.out.println("koneksi berhasil;");
            
            connection = DriverManager.getConnection(url, user, pass);

            // Buat query untuk mengambil data pengguna berdasarkan NIM
            String query = "SELECT * FROM pengguna WHERE nim = ?";
            statement = connection.prepareStatement(query);
            statement.setString(1, Nim);

            // Eksekusi query
            resultSet = statement.executeQuery();

            // Periksa apakah hasilnya tidak kosong
            if (resultSet.next()) {
                // Ambil PIN dari hasil query
                String pinFromDatabase = resultSet.getString("pin");

                // Periksa apakah PIN yang dimasukkan cocok dengan PIN dari database
                if (Pin.equals(pinFromDatabase)) {
                    isValid = true;
                } else { 
                    new login().setVisible(true);
                    
                
                    }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            // Tutup koneksi, statement, dan result set
            try {
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        return isValid;
    }
    public void hapus() {
        pinn.setText("");
        nimm.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VALIDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nimm;
    private javax.swing.JTextField pinn;
    // End of variables declaration//GEN-END:variables
}
